### ISSUE TITLE
Log progress of operations

### ISSUE THREAD

**Issue by acatav** [oribarilan/oplog#4]
There are several scenarios when it's useful to log the progress of an operation:

1. In CLI mode, for long operations it's useful to show a progress bar so the user understand what he is waiting for and how much time it's expected to take. For this scenario it would help to integrate with something like tqdm.
2. For some very long operations like model training or data processing jobs that can last even few days, it can be helpful to be able to checkout the progress of an operation while it's still running. This can be achieved by having an operation per batch of work, but it might be better to have this baked into the framework somehow

**Comment by oribarilan** [comment]
Solved by linked PR #6 . 
For docs:
https://oribarilan.github.io/oplog/tutorial/progressable_operations/
