### ISSUE TITLE
Log on operation start

### ISSUE THREAD

**Issue by acatav** [oribarilan/oplog#5]
When running an application in the CLI which doing some IO call that takes a long time, it can be helpful to log also an "operation X starting message" instead of logging only the result of the operation. Some of this operations cannot use progress bars for that in cases where the operation cannot break down to smaller steps that you can track

**Comment by oribarilan** [comment]
Solved by #7 . See `Operation(...,on_start)` flag, and `op.step` attribute (which can be `OperationStep.START` or `OperationStep.END`)
