### ISSUE TITLE
Explicit start operation flag

### ISSUE THREAD

**Issue by acatav** [oribarilan/oplog#8]
It can be helpful to have an explicit way to tell inside the log formatter if the operation is logged because it is starting to run (by setting `on_start=True`).

I would like to have my "on start" log to look like this:

```
2023-09-25 12:23:39.575646: Start my_operation
```

Instead of the default behavior:
```
2023-09-25 12:40:17.905515 (Nonems): [Creating Index / None]
```

Currently I managed to create to achieve this by adding to the formatter the following code:

```
if op.result is None:
   return f"{op.start_time_utc_str}: Start {op.name}
```
 But I prefer to be able to do something like:

```
if op.is_starting:
   return f"{op.start_time_utc_str}: Start {op.name}
```

Or 

```
if op.result == "Start":
   return f"{op.start_time_utc_str}: Start {op.name}
```

So CSV logs would make more sense

**Comment by oribarilan** [comment]
Operation has a `step` attribute. In this case, `op.step == OperationStep.START`.

The documentation is not extensive enough yet, so this is not easily discoverable.
I am working on improving the documentation, and will make sure this part is covered as well :)

Thanks!
