### ISSUE TITLE
oplog formatter don't get logs when using pytest

### ISSUE THREAD

**Issue by acatav** [oribarilan/oplog#9]
Hi,
I've created a basic test using pytest and integrated it with oplog. When I execute the test using the command pytest --log-cli-level=10 -s (with -s intended to disable log capturing), the console outputs the following message:

`INFO context_engine.knowledge_base.knowledge_base:operation.py:122 oplog: operation start`

This suggests that pytest seems to be capturing the logs instead of passing them to the oplog formatter. I've set up the logger in the package's init file.

I suspect the issue might be related to pytest configuration settings. Any assistance on resolving this would be greatly appreciated.

**Comment by oribarilan** [comment]
Note that the issue is a bit different. Pytest has its own formatter (from limited predefined alternatives), so you can't send over a custom one.

However, you are completely right that this should be supported - and it now is (solved in #10, available on v0.21.0). Thanks for raising this!
